# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{testopia}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Cyril David"]
  s.date = %q{2010-05-06}
  s.description = %q{a collection of test helpers for Ohm, Sinatra, Rack}
  s.email = %q{cyx.ucron@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/testopia.rb",
     "lib/testopia/active_merchant.rb",
     "lib/testopia/ohm.rb",
     "test/helper.rb",
     "test/test_testopia.rb"
  ]
  s.homepage = %q{http://github.com/cyx/testopia}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Because laziness is the new cuil}
  s.test_files = [
    "test/helper.rb",
     "test/test_testopia.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<contest>, [">= 0"])
    else
      s.add_dependency(%q<contest>, [">= 0"])
    end
  else
    s.add_dependency(%q<contest>, [">= 0"])
  end
end

